# Serving HTML through API Gateway for AWS Lambda
service: covid-info

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  daysSince:
    handler: handler.daysSince
    events:
      - http:
          method: get
          path: /

plugins:
  - serverless-offline